// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddWorkoutController from "./add_workout_controller"
application.register("add-workout", AddWorkoutController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RoundController from "./round_controller"
application.register("round", RoundController)

import SelectExerciseController from "./select_exercise_controller"
application.register("select-exercise", SelectExerciseController)

import ShareButtonController from "./share_button_controller"
application.register("share-button", ShareButtonController)

import VerticalCarousselController from "./vertical_caroussel_controller"
application.register("vertical-caroussel", VerticalCarousselController)
