// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


import VerticalCarousselController from "./vertical_caroussel_controller"
application.register("vertical-caroussel", VerticalCarousselController)

import SelectExerciseController from "./select_exercise_controller"
application.register("select-exercise", SelectExerciseController)
